name: Deploy Frontend to Render

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm ci

      - name: Lint
        run: npm run lint

      - name: Unit tests
        shell: bash
        run: |
            if [ -e jest.config.js ]
            then
                npm run lint
            else
                echo "Unit tests not configured!"
            fi

      - name: Deploy via Render
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}

      - name: Check if app is running
        run: |
          for i in {1..10}; do
            if curl -sSf ${{ vars.HOME_PAGE_URL }}; then
              echo "App is running!"
              exit 0
            fi
            echo "Waiting app to start..."
            sleep 10
          done
          echo "App took too long to start :(" && exit 1
